### ISSUE TITLE
0.9.5 does not seem to work on DuckDuckGo, Brave Search, MetaGer, and Mojeek

### ISSUE THREAD

**Issue by i-report-bugs** [psidex/CustomBangSearch#24] opened 2023-02-03 00:31 UTC
When you try to search on these sites using a custom bang, it does not work.

The end result is either it ignores the custom bang (Brave Search) or the search just completely doesn't proceed to load (the other three).

**Comment by psidex** [comment] 2023-02-03 01:35
Hmm, all four of those are working for me on 0.9.5. Are you able to provide anymore info about your setup?

**Comment by psidex** [comment] 2023-02-03 19:15
So it seems that this is an issue caused by Chrome/Chromium and Firefox implementing CSP slightly differently, there is an SO answer about this [here](https://stackoverflow.com/a/59548049/6396652). It does suggest a fix but annoyingly it's in the context of a normal redirect, which wont work for an extension using the `webRequestBlocking` API, which is what this extension uses.

Because of this, I don't think that there's anything that can be done.

I'm actually [planning a rewrite of custom bang search](https://github.com/psidex/CustomBangSearch/issues/18#issuecomment-1414187785), and as part of this have been considering moving the extension to use manifest v3, as Google [have decided to depracate v2 this year, or possibly next year](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/).

The issue with this is that with v3, Google are [also deciding to drop support for the `webRequestBlocking` API](https://developer.chrome.com/docs/extensions/mv3/mv3-migration-checklist/#api-blocking) ([whilst Firefox have said they will keep it](https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/)).

I've looked into it and Chromes replacement, `declarativeNetRequest`, can probably achieve similar functionality, but means things like multiple redirects (the " :: " thing) and certain search engines that use POST instead of GET requests won't work anymore.

Because of this I have been considering dropping Chrome support (once Google drop v2) and only maintaining a Firefox version. The other option would be to maintain a separate version of the extension for each browser, which would probably be a lot of work.

Since you've been quite active here recently @i-report-bugs, what do you think?

**Comment by psidex** [comment] 2023-02-04 16:22
> I haven't looked into it yet but is it not possible to just redirect the user regardless of whether the loading is blocked or not? What I mean is that as soon as the extension detects a custom bang being used, regardless of if the search service in question is already loading its own thing, the extension just calls a window.location.replace() to redirect to the proper destination while also not having an extra entry in the browser history?

That's actually a great idea! I've just tested it and it appears to work on Chrome with manifest v3. I think we'd have to wait for the page to finish loading to run the window replace JS, but most search engines are pretty quick these days.

I think I'll move forward with using that - I'll still use the blocking API on firefox but I don't think it will be too difficult to have some sort of switch, to execute the redirect one way on FF and the other on Chrome.

**Comment by psidex** [comment] 2023-04-07 17:08
I've just pushed the code ready for v0.10.0 to master, if you take a look [here](https://github.com/psidex/CustomBangSearch/blob/master/docs/supported-engines.md) I've documented the search engines that are supported for each browser.

Closing this issue as it's irrelevant for 0.10.0.

**Closed by psidex** 2023-04-07 17:08 UTC

**Comment by Aran-Fey** [comment] 2023-04-28 16:43
While checking my FF version, I noticed there was a pending update, and... now it works.

In case you still want to look into it: I've updated to v112.0.2, and I believe I was on FF v111.x before. The OS is Windows 10. Both 64-bit.

**Comment by psidex** [comment] 2023-04-28 16:58
Weird, at least it's working now! Thanks

**Comment by befocken** [comment] 2023-06-16 17:51
I was just wondering whether the proposed workaround  leads to the original request still being sent to the search engine?

Using the version 0.10.4 in a FF 114.0, it does seem to me as if the initial request is still sent to the browser's default search engine (visible for a split second).

If that's the case, this would unfortunately reduce the usage as an even more privacy-friendly alternative to the standard DDG search, wouldn't it?

p.s. very nice updates that you published @psidex, very sleek :)

**Comment by psidex** [comment] 2023-06-17 20:51
@befocken thanks 😄

So the current flow is this:

1. User writes query (which contains a bang) in search bar and presses enter
2. CustomBangSeach has an event listener on `onBeforeRequest` which is triggerred by this search
3. CBS calculates what it needs to, and then uses the `tabs.update` API to send the requesting tab to it's intended location

Because we're using the non-blocking version of `onBeforeRequest`, the browser is free to continue processing the request as step 2 and 3 happen. So yes, it's entirely likely that the request still gets sent to your search engine.

This is what I settled on for a technique that should work across all browsers and it does work well.

I don't intend for this extension to be particularly focused on privacy, although that would be nice. I'm open to suggestions if you have any!

**Comment by befocken** [comment] 2023-06-17 22:20
Ok, I see. I do have to say that for me, the main usage of this plugin would indeed be that I can use the bangs of DDG without sending its content to DDGs servers (after all, I'm using the bangs to get to the desired page directly - so why even give DDG data about it?). Of course, I might be in a minority here.

> I don't intend for this extension to be particularly focused on privacy, although that would be nice. I'm open to suggestions if you have any!

Hmm, this is of course not very simple, due to the blocking version of the request listener causing the mentioned issues.
Except for the fact, that I'm not super into the whole extension ecosystem (yet) - which is why I might not see a better solution - I could imagine a checkbox or switch in the settings (or maybe advanced settings) that you can activate in order to use the blocking version of the request listener. Of course this should then be combined with a small ?-icon which informs about its usage and limitations (such as possibly breaking the extension's functionality in Chromium-based browsers).
Another solution might, as you've initially suggested, check the browser type and switch between the blocking and non-blocking version automatically, so that at least FF users can enjoy this feature (without any extra settings or the possibility to break the extension's functionality in Chromium-based installs).

**Comment by psidex** [comment] 2023-06-21 16:35
> I could imagine a checkbox or switch in the settings (or maybe advanced settings) that you can activate in order to use the blocking version of the request listener

This could work but would probably be quite complicated, having to de-register and re-register event listeners and things like that

> Another solution might, as you've initially suggested, check the browser type and switch between the blocking and non-blocking version automatically

Yeah I'll look into doing this 😄

**Comment by psidex** [comment] 2023-07-14 19:26
@befocken I've added blocking back for firefox with the [latest commit](https://github.com/psidex/CustomBangSearch/commit/694082231f4e2bccb69d7c8d9189337d6fdf9788), it needs some more manual testing but once I'm happy I'll release a new version
